services:
  db:
    container_name: postgres_db
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD: userpassword
      - POSTGRES_USER: postgres_user
      - POSTGRES_DB: postgres_db